-- Appointment table: stores structured appointment data in MySQL
CREATE TABLE IF NOT EXISTS appointments (
  id VARCHAR(36) PRIMARY KEY,
  owner VARCHAR(255) NOT NULL,
  createdBy VARCHAR(255) DEFAULT NULL,
  patientName VARCHAR(255) NOT NULL,
  mobile VARCHAR(50) NOT NULL,
  age INT DEFAULT NULL,
  gender VARCHAR(50) DEFAULT '',
  doctorId VARCHAR(36) NOT NULL,
  doctorName VARCHAR(255) DEFAULT '',
  speciality VARCHAR(255) DEFAULT '',
  doctorImageUrl TEXT DEFAULT NULL,
  doctorImagePublicId VARCHAR(255) DEFAULT NULL,
  appointmentDate VARCHAR(20) NOT NULL,
  appointmentTime VARCHAR(50) NOT NULL,
  fees DECIMAL(10,2) DEFAULT 0,
  status ENUM('Pending','Confirmed','Completed','Canceled','Rescheduled') DEFAULT 'Pending',
  rescheduledDate VARCHAR(20) DEFAULT NULL,
  rescheduledTime VARCHAR(50) DEFAULT NULL,
  paymentMethod ENUM('Cash','Online') DEFAULT 'Cash',
  paymentStatus ENUM('Pending','Paid','Failed','Refunded') DEFAULT 'Pending',
  paymentAmount DECIMAL(10,2) DEFAULT 0,
  paymentProviderId VARCHAR(255) DEFAULT NULL,
  sessionId VARCHAR(255) DEFAULT NULL,
  paidAt DATETIME DEFAULT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_appt_doctor (doctorId),
  INDEX idx_appt_created_by (createdBy),
  INDEX idx_appt_session (sessionId),
  FOREIGN KEY (doctorId) REFERENCES doctors(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Semi-structured appointment data (notes, paymentMeta, auditLog, specialRequirements) is stored in MongoDB (AppointmentMeta collection)
